### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by arminpatel** [bsoc-bitbyte/GetIt#1]

**Comment by RISHIKESHk07** [comment]
sir, could you  assign this issue to me?

**Comment by arminpatel** [comment]
sure go ahead.
Here are some points:
- A intro of the merch site
- features
- Tech Stack
- Design

I'm sure you don't know most of it so feel free to contact me to I can brief you

**Comment by Priyansh61** [comment]
@RISHIKESHk07 Any updates?

**Comment by RISHIKESHk07** [comment]
yes sir ,i have started working on it after the  meet with @arminpatel yesterday .

**Comment by RISHIKESHk07** [comment]
# 🛒 GETIT 
 Streamlined college e-commerce: Simplifying merch buying and selling for students.

## 🌟INTRODUCTION
Streamlined college e-commerce: Simplifying merch buying and selling for students.










## ✨FEATURES

- Clubs can sell
- Buy the merch you like
- Automatic payments for sellers no need for manual verification
- Seller reports


## 💻DEVELOPED WITH

* [Visual Studio Code](https://code.visualstudio.com/) - A source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging, embedded Git control, syntax highlighting, intelligent code completion, snippets, and code refactoring


---


## 🔰 GETTING STARTED

These instructions will get you a copy of the project up and running on your local machine for development and testing purposes.

### [![My Skills](https://skills.thijs.gg/icons?i=nodejs)](https://skills.thijs.gg)PREREQUISTS

The following software is required to be installed on your system:

* Node 8.x
* Npm 3.x

Type the following commands in the terminal to verify your node and npm versions

```bash
node -v
npm -v
```

### ![NPM](https://img.shields.io/badge/NPM-%23CB3837.svg?style=for-the-badge&logo=npm&logoColor=white) BASIC SETUP

Follow the following steps to get development environment running.

```bash
# install dependencies
$ npm install

# serve with hot reload at localhost:3000
$ npm run dev

# build for production and launch server
$ npm run build
$ npm run start

# generate static project
$ npm run generate
```
## 📱 Tech Stack ![Nuxtjs](https://img.shields.io/badge/Nuxt-002E3B?style=for-the-badge&logo=nuxtdotjs&logoColor=#00DC82) ![Vue.js](https://img.shields.io/badge/vuejs-%2335495e.svg?style=for-the-badge&logo=vuedotjs&logoColor=%234FC08D)![NPM](https://img.shields.io/badge/NPM-%23CB3837.svg?style=for-the-badge&logo=npm&logoColor=white)

[![My Skills](https://skills.thijs.gg/icons?i=vue,nuxt,nodejs)](https://skills.thijs.gg)
### <img src="https://icons8.com/icon/53450/webBACKEND">FRONTEND:
- VUE (https://vuejs.org/guide/introduction.html)
- NUXT(https://nuxt.com/docs)

### BACKEND: 

TO BE UPDATED


## 🎨DESIGN 
- [![My Skills](https://skills.thijs.gg/icons?i=figma)](https://skills.thijs.gg) 
 
  
## HOW TO CONTRIBUTE?

[Contributing.md](https://github.com/bsoc-bitbyte/GetIt/blob/main/CONTRIBUTING.md)


## PRODUCT PREVIEW
 - FIGMA LINK FOR THE PROJECT(https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=0-1&t=YsftuOHwePR2R58Z-0)

</br>
</br>

 ![image](https://github.com/bsoc-bitbyte/GetIt/assets/117551967/90fe6b06-3515-481c-af34-d92da8faac92)

</br>
</br>

![image](https://github.com/bsoc-bitbyte/GetIt/assets/117551967/1875a09c-9e69-43ed-a995-d53aed03109f)


</br>
</br>

**Comment by RISHIKESHk07** [comment]
Is there any changes required to be done?

**Comment by arminpatel** [comment]
@RISHIKESHk07 there's no need to do this 😅 ... just raise a pull request
