### ISSUE TITLE
[Feature Request]: Checkout Page

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#10]
### Is your feature request related to a problem? Please describe.

Make the checkout page as per figma design and make it responsive.
It is required to use tailwindcss for styling the page.

![Checkout page (1)](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/12af42d4-b396-4237-b011-4259d9e67441)

**Figma ** [Link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=172-773&t=JGyT4UF8QadJWt3u-0)

### Describe the solution you'd like

Make it inside the pages directory.

**Comment by Predcodes69** [comment]
Hello @tushitshukla03 , i am interested in working on this issue. Can you please assign it to me?

**Comment by Priyansh61** [comment]
@Predcodes69 Any updates on this?

**Comment by Predcodes69** [comment]
@Priyansh61 Yes, working on this, will give you updates by today evening.

**Comment by Predcodes69** [comment]
@Priyansh61 The pr will be ready latest by 11th June.

**Comment by Predcodes69** [comment]
Update: I am working on this issue and trying to solve it as soon as possible.

**Comment by Priyansh61** [comment]
Please try to speed up we are waiting :crossed_fingers:

**Comment by Predcodes69** [comment]
Yes @Priyansh61 , I am on it.

**Comment by Predcodes69** [comment]
Update: The mobile design is almost ready, incorporating form handling for the page, working on responsiveness now.

**Comment by Priyansh61** [comment]
@Predcodes69 When can we expect the PR?
