### ISSUE TITLE
[Feature Request]: add tests for `tickets` app

### ISSUE THREAD

**Issue by aryan1113** [bsoc-bitbyte/GetIt#118]
in backend/tickets/tests.py create tests for the tickets app

**Comment by Priyansh61** [comment]
@aryan1113 Status for the issue?

**Comment by aryan1113** [comment]
shared basic tests with @arminpatel, back on 26th Jan
tests for few combinations of params and API endpoints were missing, so we postponed work on it. 
I'll resume work on this from next week !
