### ISSUE TITLE
Refactor : Implementation of Tailwind CSS on Sign-up and Sign-in Page 

### ISSUE THREAD

**Issue by krushn-a** [bsoc-bitbyte/GetIt#16]
### Is your feature request related to a problem? Please describe.

Both the Sign-up and Sign-in pages currently have normal CSS

### Describe the solution you'd like

Tailwind CSS needs to be implemented on both pages instead of normal CSS.

**Comment by arminpatel** [comment]
Reference: #12

**Comment by Predcodes69** [comment]
@arminpatel I am interested on working on this issue, I can do the needful, so can you please assign it to me?

**Comment by arminpatel** [comment]
Sure @Predcodes69, go ahead
