### ISSUE TITLE
[Feature Request]:  Design dashboard of the website

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#18]
### Is your feature request related to a problem? Please describe.

Make the dashboard according to the Figma design and ensure it is responsive. Please utilize Tailwind CSS for styling the page. All the necessary details are provided in the design.

https://www.figma.com/file/WYMbU5wej8z0i7o2wKI6y5/Getit-design?type=design&node-id=0-1&t=ZkVPHg1qShpVFcxf-0

### Describe the solution you'd like

For now, please hardcode the username and details since the backend is not yet integrated.

**Comment by Predcodes69** [comment]
Hello @prernadabi23 , I am interested in working on this issue. Can u please assign it to me?

**Comment by prernadabi23** [comment]
@Predcodes69 I see that you are already working on two issues. Why don't you finish them off? If someone still hasn't taken this issue, then I'll assign it to you.

**Comment by Predcodes69** [comment]
@prernadabi23 Hey, I am waiting for a review on one of them, I raised the pull request on it last night . As far as the other issue is concerned, it is also completed, but have to incorporate components in it for the various sub parts of the design so that it is easier to link it to the backend.

**Comment by prernadabi23** [comment]
Assigned @Predcodes69.

**Comment by Predcodes69** [comment]
Thanks @prernadabi23 , will try to resolve the issue ASAP.

**Comment by abansal15** [comment]
Hello @prernadabi23 i would like to would like to work on the issue can you please assign it to me ?

**Comment by prernadabi23** [comment]
I am assigning it to @abansal15.
@Predcodes69, please prioritize resolving both of your issues first.
