### ISSUE TITLE
[Feature Request]: Add favicon for Getit

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#185]
### Is your feature request related to a problem? Please describe.

Currently, Getit lacks a favicon. Having a favicon offers numerous benefits for a web application.

### Describe the solution you'd like

Add the favicon shown in the 'Finalised' section in this figma 
https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=85-727&t=8HJ1iB0tvEkwQimf-0 

### Developer Help

Refer this to know more about a favicon - https://www.bluehost.com/blog/what-is-a-favicon/#Where_do_favicons_appear

#### General notes for Developers:
Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you. Once assigned, feel free to submit a PR.

**Comment by yashpatil641** [comment]
@AkashPaloju i want to work on this issue

**Comment by aniket0742** [comment]
@AkashPaloju Sir, I would like to work on this issue regarding addition of favicon to the GetIt website. Based on the finalized favicon provided in the Figma file, I will make changes in the index file and implement the required changes. 
Thank You.

**Comment by Kushdapush** [comment]
@yashpatil641 Go on start working on this 👍 
@aniket0742 we will be releasing some more issues so stay tuned...
