### ISSUE TITLE
[Feature Request]: Redesign the event card

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#189]
### Is your feature request related to a problem? Please describe.

The current event card does not align with the UI of the new merch card. Therefore, the event card requires a slight redesign.

### Describe the solution you'd like

Redesign the event card as shown in this [figma](https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=243-662&t=OLb2z0ufQX6Bt0FU-0) (Please refer to the event card in the finalized section only)

#### General notes for Developers:
Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by yashpatil641** [comment]
@AkashPaloju I want to work on this issue i will redesign the event card as given in the figma file, I will be making changes in eventsList.vue file and use tailwind css to redesign the card.

**Comment by Kushdapush** [comment]
Go ahead @yashpatil641
