### ISSUE TITLE
[Feature Request]: Redesign Events page

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#191]
### Is your feature request related to a problem? Please describe.

Redesign the events page

### Describe the solution you'd like

Please refer to the 'events' frame only in this figma - https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=369-845&t=iV6PY9Yd5rLQIy46-0

#### General notes for Developers:
Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by yashpatil641** [comment]
@AkashPaloju I want to work on this issue i will be making changes in the eventList.vue file and use tailwind css to achieve the look as given in the figma file

**Comment by Kushdapush** [comment]
Hey @yashpatil641 , would you like to work on #192 instead  ??

**Comment by yashpatil641** [comment]
> Hey @yashpatil641 , would you like to work on #192 instead ??

Yes, I would

**Comment by Kushdapush** [comment]
Great, comment there and ill assign you the issue #192 , this issue(#191) is open as of now

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju  I would like to work on this issue

**Comment by ANIRUDHNARANG0** [comment]
i would make changes in eventList.vue and use tailwind.css
