### ISSUE TITLE
[Feature Request]: Add Products Page

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#192]
### Is your feature request related to a problem? Please describe.

Create the Products Page as part of the merch section implementation

### Describe the solution you'd like

Please refer to the 'products' frame only in this figma -
https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=369-654&t=iV6PY9Yd5rLQIy46-0

#### General notes for Developers:
Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by yashpatil641** [comment]
@AkashPaloju I would like to work on this issue, i will be adding a productsList.vue file using the merchcard component and tailwind css to style the page as given in the figma file

**Comment by Kushdapush** [comment]
Go on 👍
