### ISSUE TITLE
[Feature Request]: Add the carousel section to the home page

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#196]
### Is your feature request related to a problem? Please describe.

Currently we don't have any elements on the home page to showcase most popular events on the homepage of the website to attract the audience

### Describe the solution you'd like

Add the carousel in the home page according to the [figma](https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=227-893&t=IJopOIRCtyjswZQr-0)

(Don't forget to add the hover effect)

### General notes for Developers:

Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju i would like to work on this issue

**Comment by yashpatil641** [comment]
@AkashPaloju I would like to work on this issue i will be making changes in the index.vue file and use tailwind css to acheive the desired look.

**Comment by Kushdapush** [comment]
> @AkashPaloju I would like to work on this issue i will be making changes in the index.vue file and use merchcard and eventcard components with tailwind css to acheive the desired look.

Hey @yashpatil641 mind checking out the issue #197

**Comment by Kushdapush** [comment]
Hey @ANIRUDHNARANG0 please follow the standard procedure to ask for issue assignments!!

**Comment by ANIRUDHNARANG0** [comment]
@Kushdapush  sorry would take care of it ,
i want to work on this issue and make  carousel in index.vue page and add styling using tailwind css  refering to figma file

**Comment by Kushdapush** [comment]
Ok we will be breaking this issue in 2 parts.
The Carousal part will go to @yashpatil641 and the Products and Event cards display will go to @ANIRUDHNARANG0 
for now @ANIRUDHNARANG0 please comment on the other issue #198
