### ISSUE TITLE
[Feature Request]: Implement the Email verification feature

### ISSUE THREAD

**Issue by Kushdapush** [bsoc-bitbyte/GetIt#197]
### Is your feature request related to a problem? Please describe.

Currently there is no way to verify if a user is signing up with their official email address. We need to figure this out

### Describe the solution you'd like

A simple solution would be to send the users a confirmation mail on the email address that they are using to signup.
We can generate a verification token that would be sent via the confirmation mail. This token can be in the form of a link etc. When the user clicks on the link then only we will allow them to create an account.

We will divide this issue in two parts, in the first part we will deal with setting a SMPT server and sending a mail when the user tries to login.
In the second part we will aim to generate the verification token and verify the users when they click on it.

### Describe alternatives you've considered

You will find a preexisting SMTP config, we will start building upon it 

### Developer Help

https://www.youtube.com/watch?v=wB1qOExDsYY
Here's a tutorial that explains the task we are going to perform.

**Comment by Om-Thorat** [comment]
Helloo! I would like to work on this issue. My approach would be to setup the smtp server according to the prebuilt config, futher to validate the user by a link on signup a link containing a verfication toekn will be sen to their mail further activating their login on the main page and changing the status of their user model in db to activated, by having a different field. on further login email verfication won't be required but we can make give an option to the user to just use it as 2 factor auth. will be doable in the same way.

**Comment by Kushdapush** [comment]
Great, Go on @Om-Thorat 👍
