### ISSUE TITLE
[Feature Request]: Add the Events, merch section to the home page

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#198]
### Is your feature request related to a problem? Please describe.

Add merch, events section

### Describe the solution you'd like

[figma](https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=227-893&t=evW7D3NNgYC8rqk8-0)

(don't forget to add hover effects on buttons given in figma)

### General notes for Developers:

Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju  i want to work on this issue will make the desirable changes using tailwind css acc to figma file

**Comment by ShashaankS** [comment]
@AkashPaloju I am new to open source but i would like to work upon this, by adding merch and events section to the index.vue file, using card and grid from tailwind in according to figma file

**Comment by Kushdapush** [comment]
> @AkashPaloju I am new to open source but i would like to work upon this, by adding merch and events section to the index.vue file, using card and grid from tailwind in according to figma file

Hey @ShashaankS I really like your Enthusiasm but this issue is not beginner friendly, we will soon release some good first issues and will assign you one, till then please stay tuned 👍

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju i have edited my approach
