### ISSUE TITLE
[Feature Request]: Add footer

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#200]
### Is your feature request related to a problem? Please describe.

Currently, users may have difficulty finding essential information, navigating to key pages, and connecting with our social media profiles, impacting their interaction with the site.

### Describe the solution you'd like

Add the footer given in this [figma link](https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=806-3049&t=oX422Ry3uIaBwiPR-0).

Links (All these 4 links should open in a new tab) : 
1.mail : theprogclub@iiitdmj.ac.in (tentative)
2.discord: https://discord.com/invite/W6crw7ajSs
3.Report a bug: https://github.com/bsoc-bitbyte/GetIt/issues/new?assignees=&labels=bug&projects=&template=1_bug_report_form.yml&title=%5BBUG%5D%3A+

4.Edit this page:  This link should redirect to "code file on github" according to which page user in , when clicking.
for example - If the user is in events page , the link should point to  [eventList.vue](https://github.com/bsoc-bitbyte/GetIt/blob/main/frontend/pages/eventList.vue). 

  

### General notes for Developers:

Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation makes sounds good, we'll assign the issue to you.

**Comment by ShashaankS** [comment]
@AkashPaloju I will create a new vue component according to figma file using tailwind css, and attach all the social handles mentioned and use the current address of the page to redirect users to the concerned code page on github.
