### ISSUE TITLE
[Feature Request]: Add "Product details" page

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#206]
### Is your feature request related to a problem? Please describe.

Currently we don't have the product details page

### Describe the solution you'd like

https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=930-740&t=1jjSHLWA3KQ7UPHf-0

Add the product details page according to the figma

### Developer Help

Refer how the [event details page](https://github.com/bsoc-bitbyte/GetIt/blob/main/frontend/pages/events/%5Bid%5D.vue) is implemented in Getit

### General notes for Developers:

Once you have a good understanding of the issue, you can ask for it to be assigned to you by leaving a comment as follows: Explain clearly how you'd tackle the issue at a minimum, point to which file(s) (mention their links in the repo) you'd modify, and describe the changes you'd make. If creating new files is necessary, specify where you would place them and outline the content you would add to resolve the issue.

If your explanation sounds good, we'll assign the issue to you.

**Comment by yashpatil641** [comment]
I would like to work on the issue i will create a new id.vue file inside the products folder and use tailwind css for styling

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju  i would like to work on this issue i would use vue icons to add desirable icons in buttons and would tailwind.css for further css, for size i woul pass a list and allow user to chose from it using radio andn  for product detail i will create an accordian

**Comment by ANIRUDHNARANG0** [comment]
for share i would pass on click on it

**Comment by ShashaankS** [comment]
@AkashPaloju I would like to work on this issue, I will be implementing dynamic visibility toggles for the "Size Chart" and "Product Details" sections using Vue.js. Utilize Vue's v-show directive to toggle visibility based on user's click.
 For share button that will copy to clipboard the current url of the webpage to generate correct product URLs dynamically.
 Fetch product data from Django backend via API calls and related products as well.

**Comment by Kushdapush** [comment]
ok, we will go forward with @ShashaankS this time.

**Comment by Kushdapush** [comment]
Also feel free to ask any doubts or for help
