### ISSUE TITLE
[Feature Request]: modify navbar

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#207]
### Is your feature request related to a problem? Please describe.

As part of the Admin dashboard project, we require a profile dropdown to offer dashboard navigation options in the navbar for admins and so forth in the future

### Describe the solution you'd like

Add the profile dropdown and update the navbar according to the design in Figma. Show the "Sign in" button if the user is not logged in, and if the user is logged in,  display the profile button and the dropdown when clicked on it. The dropdown should close when the user clicks on the profile button or on any other area (excluding the dropdown) on the page (like we see on the other websites).

https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=787-2965&t=Pzow0VuWVGSotgy1-0

### Developer notes

Please detail how you manage the conditional presentation of the "Signin" button and the "profile" button, as well as explain the implementation of the UI of the dropdown.

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju i want to work on this issue

**Comment by ANIRUDHNARANG0** [comment]
in this i will redirect user to sign using nuxt link

**Comment by yashpatil641** [comment]
I would like to work on this issue i will use v-if conditions for checking if the user is authenticated or not and show sign-in button or profile icon accordingly. when user clicks on profile icon a card will show up with usre info which i will fetch from backend and make sure that when a user clicks anywhere on the screen the condition for v-show of profile component is set to false excluding the dropdown. I will be making changes in the navnew.vue file.
