### ISSUE TITLE
[Feature Request]: Add Admin dashboard button in navbar profile dropdown

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#209]
### Is your feature request related to a problem? Please describe.

Only Admin users should be able to go to the Admin dashboard page through navbar.

### Describe the solution you'd like

Add the "Admin dasboard" button in the profile dropdown. This button should be visible only to users who are admins. 

https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=1224-758&t=gZywg2uGbycc4BVV-0

Note: Just create a blank "Admin dashboard" page in this issue, no need to create the full UI for the admin dashboard page.

### Developer Notes
Explain how you will identify a user whether they are an admin user or not ? (Refer this [model](https://github.com/bsoc-bitbyte/GetIt/blob/main/backend/accounts/models.py) )
and how you manage to display the dashboard  button if the user is an admin ?

**Comment by yashpatil641** [comment]
I would like to work on this issue i will conditionally render the  "Admin dasboard" button by checking whether user is admin or not which i will do by checking if is_admin field i true or false and show or hide the button respectively for which i will be adding is_admin field to serializers.py.
