### ISSUE TITLE
[Feature Request]: Add Admin dashboard sidebar and add AdminLayout

### ISSUE THREAD

**Issue by AkashPaloju** [bsoc-bitbyte/GetIt#212]
### Is your feature request related to a problem? Please describe.

Part of the Admin dashboard project

### Describe the solution you'd like

Add the Sidebar and 4 pages shown in the figma.  You don't need to implement the pages' UI , just 4 blank pages but all the 4 pages should contain the side bar.

These 4 pages should only be accessible by clicking the "Admin Dashboard" button in the profile dropdown. The "Add new Product page" should be the default page when the admin dashboard button is clicked.

https://www.figma.com/design/5Hs4DlvyJJWjQB9K7Fh0CY/Getit?node-id=1270-795&t=uVrkfzfV464gRQZ9-0

(Don't forget to change the text color of the active page's name in the sidebar)

### Developer Notes

Please include how you'd change the text color of the active page's name in the sidebar ?
As all these four pages should be visible only to admins, explain how do you restrict normal users from accessing these pages even if they enter the correct URL in the address bar? For example, if a normal user logs in and enters the URL of the 'Add New Product' page correctly (https://merch-site.netlify.app/addNewProduct), they should only see a 404 page.

**Comment by kartik-grg** [comment]
@AkashPaloju  I would like to work on this issue, i would be creating a component for sidebar, i will create four blank pages and import sidebar component in each of them. For changing the text colour for selected page i will be giving a different class on the onClick event and using nuxtlink for displaying the respective page. For restricting these pages from normal users i will be checking whether the user is admin or not by fetching current user logged in info.

**Comment by kartik-grg** [comment]
@AkashPaloju I have made the required changes for the admin dashboard, please review the changes

![Screenshot from 2024-07-24 15-27-57](https://github.com/user-attachments/assets/a78423c2-edf6-48b8-81dd-06858ec0691b)
[Screencast from 07-24-2024 03:28:18 PM.webm](https://github.com/user-attachments/assets/5fc7575c-713b-4eeb-8f90-a43a7022fcef)

[Screencast from 07-24-2024 03:29:05 PM.webm](https://github.com/user-attachments/assets/199649b1-c4ce-48b5-b19b-604b6ee068e0)
I have used middleware for restricting non admin users to view the admin dashboard pages
