### ISSUE TITLE
[BUG]: Bottom section on the Signup Page has White Margin

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/GetIt#22]
### Describe the bug

When you go to `/signup`, on some of the mobile displays such as "Iphone SE" there is a white margin on the bottom of the page.

### Steps To Reproduce

1. Go to localhost:3000/signup

2. Scroll down to bottom

3. See the white margin at the bottom.

### Expected Behavior

The little greyish background should be all over the display, instead of white one. 

Check for all the mobile and Desktop display that the background is even everywhere.

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/GetIt/assets/96513964/ee38cda5-c7ea-460c-9270-8c1b1636405e)

### What device are you using?

Desktop

**Comment by Doraemon012** [comment]
@Priyansh61 I would like to work on this issue, please assign this to me.

**Comment by Priyansh61** [comment]
Yeah go Ahead. But check if there is a PR open for it

**Comment by Predcodes69** [comment]
I am interested in working on this issue, can u please assign it to me?

**Comment by thejaysharma** [comment]
Okay @Predcodes69 do it as soon as possible.
