### ISSUE TITLE
[Feature Request]:  Add Navbar to all the Routes

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/GetIt#23]
### Is your feature request related to a problem? Please describe.

Currently the navbar is only visible at the landing page, when user goes to signin / signup / product page the navbar disappears.

### Describe the solution you'd like

The Navbar should be present on all the routes and at the top of the page.

### Developer Help

Find a way to keep the navbar in the `index.vue` and then use some sort of `router-outlet` to display the contents of the routes being used.

Now other way could be importing the navbar in all the pages, signin, signup but I guess that's not a good option so see how we can go with the above approach.

**Comment by Predcodes69** [comment]
Hello @Priyansh61 , i am interested in working on this issue, can u please assign me this issue?

**Comment by Priyansh61** [comment]
@Predcodes69 Please complete your previous issues and then you can work on it, and till then let the other folks give a try

**Comment by jainvedant392** [comment]
@Priyansh61 I am willing to work on this issue. Could you please assign it to me? I will keep in mind to display navbar at every page by adding it to all the routes

**Comment by Priyansh61** [comment]
Definitely! @jainvedant392

**Comment by Predcodes69** [comment]
I am interested in working on this issue. Can you please again if to me?

**Comment by Priyansh61** [comment]
@Predcodes69 Could you please raise the PR for the https://github.com/bsoc-bitbyte/GetIt/issues/56? and then work on this?

**Comment by Predcodes69** [comment]
> @Predcodes69 Could you please raise the PR for the https://github.com/bsoc-bitbyte/GetIt/issues/56? and then work on this?

Okay sure.

**Comment by Predcodes69** [comment]
Working on it. Will raise the PR for all the issues ASAP

**Comment by abansal15** [comment]
@Priyansh61 i would like to work on this issue please assign this issue to me....

**Comment by Priyansh61** [comment]
@abansal15 You already have a major issue assigned complete that first kindly

**Comment by prernadabi23** [comment]
This issue is available for anyone who wants to work on it. Please comment here if you are interested.

**Comment by abansal15** [comment]
please assign to me

**Comment by abansal15** [comment]
@prernadabi23 please aasign this issue to me

**Comment by prernadabi23** [comment]
Could you let me know when you can resolve this issue? @abansal15

**Comment by abansal15** [comment]
@prernadabi23 i will resolve the issue till tomorrow evening

**Comment by abansal15** [comment]
@prernadabi23 please assign this issue to me

**Comment by Priyansh61** [comment]
@abansal15 I have already informed you, complete your PR on BSoC website first, then get  assigned to new issues.

**Comment by rrtk857** [comment]
@Priyansh61, Please assign this issue to me.

**Comment by abansal15** [comment]
> @abansal15 I have already informed you, complete your PR on BSoC website first, then get assigned to new issues.

@Priyansh61 i have completed my pr of hamburger it is in review process in the pr of ui of leaderboard i have done some design which is in review therefore currently i am doing nothing

**Comment by Priyansh61** [comment]
Go ahead! and please test it thoroughly before raising the PR.

**Comment by rrtk857** [comment]
@Priyansh61, Sure
