### ISSUE TITLE
[BUG]:  Extra White Space at the Bottom of Page

### ISSUE THREAD

**Issue by thejaysharma** [bsoc-bitbyte/GetIt#24]
### Describe the bug

A little amount of excess white space appears at the bottom of the page when you navigate to "/signin."

### Steps To Reproduce

1. Go to localhost:3000/signin

2. Scroll down to bottom

3. See the white margin at the bottom.

### Screenshots/Videos

![Screenshot_20230622_123021](https://github.com/bsoc-bitbyte/GetIt/assets/96112110/b0a514f2-9821-4b68-9c35-abc6740f497f)
![Screenshot_20230622_123100](https://github.com/bsoc-bitbyte/GetIt/assets/96112110/afca35b6-05f4-46c4-915b-8ade2e36148b)

### What device are you using?

Desktop, Mobile

### What browsers are you seeing the problem on?

Chrome

**Comment by Predcodes69** [comment]
Hello @thejaysharma , i am interested in working on this issue, can u please assign me this issue?

**Comment by Akash1965** [comment]
Hi @thejaysharma I can help in this issue.
Please assign this to me

**Comment by Priyansh61** [comment]
@Akash1965 Go ahead!

**Comment by Akash1965** [comment]
I've made a PR @Priyansh61
I hope you'll like it
Please leave a review and let me know if there's any modification required

**Comment by Akash1965** [comment]
I've made a PR @Priyansh61
I hope you'll like it
Please leave a review and let me know if there's any modification required
