### ISSUE TITLE
[BUG]: Image dimensions affecting product page visibility and user experience

### ISSUE THREAD

**Issue by thejaysharma** [bsoc-bitbyte/GetIt#26]
### Describe the bug

Image Dimensions of the product are not good in `/products/_id`.

### Steps To Reproduce

1. Go to localhost:3000/products/_id

2. See the Product Image.

### Expected Behavior

The image box should not change with the size of the image and should have a fixed dimenssion.
### Screenshots/Videos

![Screenshot_20230622_123705](https://github.com/bsoc-bitbyte/GetIt/assets/96112110/55cd09e3-f9ac-4a8b-9634-27a2b089b3d5)

### What device are you using?

Desktop, Mobile

### What browsers are you seeing the problem on?

Chrome

**Comment by Doraemon012** [comment]
@thejaysharma I would like to work on this issue. Please assign this to me.

**Comment by thejaysharma** [comment]
@Doraemon012 Go ahead!

**Comment by Priyansh61** [comment]
@Doraemon012 Updates?
