### ISSUE TITLE
[Feature Request]: Buy Now and Add to Cart should stick at the bottom of the product page.

### ISSUE THREAD

**Issue by Priyansh61** [bsoc-bitbyte/GetIt#27]
### Is your feature request related to a problem? Please describe.

Currently when the user scrolls down the product page the buy now and add to cart button goes up, so in order to click them the user has to go back up again to buy/add the product.

### Describe the solution you'd like

Both the buttons should stick at the bottom of the page and should have position fixed when the user scrolls the page.

### Developer Help

You can see the button should be similar to what flipkart uses currently.

![image](https://github.com/bsoc-bitbyte/GetIt/assets/96513964/d31f33a9-233c-45f0-9c4c-a281b85a6139)

**Comment by shramanpaul** [comment]
Hello @Priyansh61 , I am interested in working on this issue, can u please assign it to me?

**Comment by Priyansh61** [comment]
Yeah! Go ahead!!
