### ISSUE TITLE
[BUG]: Unable to select the radio button while clicking on text of product sizes.

### ISSUE THREAD

**Issue by thejaysharma** [bsoc-bitbyte/GetIt#28]
### Describe the bug

We are not able to select the product size when clicking on text of the product sizes. It is selecting while clicking on radio button only.

### Steps To Reproduce

1. Go to localhost:3000/products/_id

2. Choose the size on clicking on the text of the sizes.

### Expected Behavior

The button should be clickable even when the person clicks on the text, not just the radio button.

### Screenshots/Videos
![Screenshot_20230622_130140](https://github.com/bsoc-bitbyte/GetIt/assets/96112110/0a772586-3827-4480-8d3d-e0710c6c0267)

### What device are you using?

Desktop, Mobile

### What browsers are you seeing the problem on?

Chrome

**Comment by rrtk857** [comment]
@thejaysharma, Please assign this issue to me.

**Comment by thejaysharma** [comment]
@rrtk857 Go ahead!

**Comment by Priyansh61** [comment]
@rrtk857 updates?

**Comment by rrtk857** [comment]
@Priyansh61, I have fixed it and pushed changes in the PR.

https://github.com/bsoc-bitbyte/GetIt/assets/129523259/89c061d7-4b6b-4f92-9e51-8efb61e9b6b0

**Comment by Priyansh61** [comment]
@rrtk857 Can you raise a different PR for this, and keep the navbar one seperate, it will help us keep commits organized.
