### ISSUE TITLE
[Feature Request]:  Make the Pages Align in Center

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#30]
### Is your feature request related to a problem? Please describe.

Make sure the website pages are centered but don't forget to keep them responsive. Also, center align the shop, sign-in, and sign-up pages.

![Screenshot from 2023-06-22 13-36-02](https://github.com/bsoc-bitbyte/GetIt/assets/104578155/654b1729-0c51-4544-b217-e16fe38aac41)

### Describe the solution you'd like

![Screenshot from 2023-06-22 13-44-56](https://github.com/bsoc-bitbyte/GetIt/assets/104578155/9abbaf40-ced4-4003-ad7e-59203775df6e)

For reference you can see here.,

**Comment by Doraemon012** [comment]
I would like to work on this issue, please assign this to me.

**Comment by prernadabi23** [comment]
@Doraemon012 Please complete all of your previous tasks, and then I will assign it to you.

**Comment by anshikkay** [comment]
@prernadabi23 i would like to work on this issue, for making the pages align center, i will be using css
thank you.

**Comment by prernadabi23** [comment]
@anshikkay Can you use Tailwind CSS because the entire website is built with Tailwind?

**Comment by anshikkay** [comment]
@prernadabi23 sure!!

**Comment by prernadabi23** [comment]
Then go ahead @anshikkay :)

**Comment by prernadabi23** [comment]
The lines below the headlines extend beyond the center, and you can only begin after the issues related to the shop page are merged. You can address this issue later when the PR is merged, and the page needs to be centrally aligned, like reducing the space between the details and the images.

@anshikkay

**Comment by prernadabi23** [comment]
As this issue is being addressed in other PRs, I am closing this issue.
@anshikkay
