### ISSUE TITLE
[Feature Request]:  Cart 

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#31]
### Is your feature request related to a problem? Please describe.

Make the cart component.
![cart 1](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/53041d78-a3ef-42ca-a696-e1e7a68555be)
Use tailwind. 

Figma [Link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=111-662&mode=design&t=YMOL6ZQXtmpyvViB-0)

### Describe the solution you'd like

make the cart as shown in image as a component.

**Comment by Doraemon012** [comment]
@tushitshukla03 I would like to work on this issue, please assign this to me.

**Comment by Kushdapush** [comment]
@tushitshukla03  @Priyansh61 I would like to work on this issue, I will make a single file component named cart.vue under the product folder to make the cart

**Comment by tushitshukla03** [comment]
@Kushdapush you can work on this
