### ISSUE TITLE
Implement navbar component 

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#4]
### Tasks

- the design for the navbar is given in figma file. If you have any good idea feel free to share it.
- Try to make it responsive
- Figma design for reference [Link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=0-1&t=gUt6o77XfJCG9Bki-0)

### Guidance

The file will be created inside the components directory.
It is required to use tailwindcss.

**Comment by abansal15** [comment]
Pls assign this issue to me

**Comment by abansal15** [comment]
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/a6377b54-dce2-46eb-a0cb-44985edc1da9)
i can add this nav bar using flex

**Comment by shreyashkatkar07** [comment]
Hi @tushitshukla03, I would like to work on this issue. Could you please assign it to me ?

**Comment by Predcodes69** [comment]
Hello @tushitshukla03, I am interested in working on this issue, can u please assign it to me?

**Comment by tushitshukla03** [comment]
We are keeping this issue open in case someone else wants to contribute and if it remain open even after closing of your card issue which is assigned to you then you can take this one also.

**Comment by whizzy23** [comment]
I would like to work on this issue , can you please assign this issue to me. @tushitshukla03

**Comment by tushitshukla03** [comment]
@whizzy23 You can now work on this.

**Comment by whizzy23** [comment]
@Priyansh61 working on its responsiveness , almost done...

**Comment by whizzy23** [comment]
tommorow maybe

**Comment by prernadabi23** [comment]
Are you experiencing any issues?
@whizzy23

**Comment by whizzy23** [comment]
I am done with the navbar , just taking reviews from @tushitshukla03 and implementing them .... @prernadabi23
