### ISSUE TITLE
[BUG]: Responsiveness Issue of Signin and SIgnup pages 

### ISSUE THREAD

**Issue by Predcodes69** [bsoc-bitbyte/GetIt#56]
### Describe the bug

The code is not supported for the tablet devices such as Ipad or Ipad mini.

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/04238391-b244-4cc9-a1ca-6f01ba4d988c)

**Comment by prernadabi23** [comment]
This issue has already been solved in #55 by you, so please close this issue. And if not, please complete that issue in that particular thread.
@Predcodes69.

**Comment by Predcodes69** [comment]
![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/02e443ac-388d-4a84-819f-67c1ac31dce7)
![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/326d1704-8dae-49de-8db8-f4446c35410d)

Are the image dimensions and the background-color fine now? @prernadabi23 
Plus the tablet views are fixed now.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/a08e257a-8e44-4bff-b389-f138b49e7bed)
So, shall i commit push the changes? @thejaysharma @prernadabi23

**Comment by prernadabi23** [comment]
There is still extra space between the inputs and the two buttons: "Sign In" and "Sign In With Google".
@Predcodes69

**Comment by Predcodes69** [comment]
Okay, on it. Incorporating form as well in these two pages so as to facilitate linking to backend

**Comment by Predcodes69** [comment]
The image length is fine now right? @prernadabi23

**Comment by prernadabi23** [comment]
Yes @Predcodes69

**Comment by Predcodes69** [comment]
> Yes @Predcodes69

Okay. Pushing the changes soon
