### ISSUE TITLE
[BUG]: Responsiveness issue of Navbar 

### ISSUE THREAD

**Issue by Predcodes69** [bsoc-bitbyte/GetIt#58]
### Describe the bug

The navbar is not fully responsive, the main page content is overlapping with the navbar contents.

### Screenshots/Videos

![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/c3962fc3-7b4c-4920-8c64-f6dbc4e457a0)
![image](https://github.com/bsoc-bitbyte/GetIt/assets/113824146/08d6e745-6a61-4737-8eb2-e43220f4e85a)

### Additional context

Can be fixed by giving the navbar it's own div and making it's position fixed and some more modifications

**Comment by prernadabi23** [comment]
@Predcodes69 The navbar is being implemented in Tailwind. Please have patience; that PR has not been merged yet.
