### ISSUE TITLE
[Feature Request]: Changes in Sign-in and Sign-up Page.

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#59]
### Is your feature request related to a problem? Please describe.

In Figma design, the image occupies the entire length, and there is extra space between the inputs. For the signup page, please set the background color to white.

### Describe the solution you'd like

[Link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=0-1&mode=design&t=x9ZfFFqYd1CryDPO-0)

**Comment by Predcodes69** [comment]
@prernadabi23 its being addressed by me in another recently opened issue

**Comment by prernadabi23** [comment]
@Predcodes69 I am not talking about the responsiveness of the pages.

**Comment by Predcodes69** [comment]
@prernadabi23 I am already working on fixing the responsiveness issues and the design issues of the sign in and sign up pages as discussed with @thejaysharma, and as for the earlier issue, i solved only the extra white space bug of the sign in page, #24

**Comment by prernadabi23** [comment]
@Predcodes69 Okay then make all these changes.
