### ISSUE TITLE
[Feature Request]: Items in the navbar are not so much attarctive

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/GetIt#62]
### Is your feature request related to a problem? Please describe.

Items in the nav bar is not attarctive.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/f0222820-cb21-4d1e-a538-7792226bb804)

### Describe the solution you'd like

The items should have some hover effect and some good font style.

### Describe alternatives you've considered

I will add some amazing hover effect and change the font style

**Comment by abansal15** [comment]
@Priyansh61 please assign this issue to me .

**Comment by Priyansh61** [comment]
Do we need this upgrade currently?

cc @prernadabi23 @thejaysharma @tushitshukla03

**Comment by prernadabi23** [comment]
There is no need at the moment. @Priyansh61
