### ISSUE TITLE
[Feature Request]: Sign up and Sign In page

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#7]
### Is your feature request related to a problem? Please describe.

Create the sign in and sign up page as per figma design. Navbar is a diffrent issue skip  that part.

![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/8f2c6a18-a176-4452-8187-138b0c7a3235)

**Figma Link** [Click me](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=0-1&t=N7gzCAsanbXlvwoI-0)

### Describe the solution you'd like

Inside the pages folder, create Signin.vue and Signup.vue files and make it responsive and remove the illustration in mobile view

**Comment by krushn-a** [comment]
Hello @tushitshukla03 I Would like to work on this issue. Can you please assign me this issue.

**Comment by tushitshukla03** [comment]
Sure, You can work on this

**Comment by krushn-a** [comment]
Hello  @tushitshukla03 i was running the local host website and it showing me a page from which i could not able to sort out how to proceed further. Could you please help me out
![2023-06-03](https://github.com/bsoc-bitbyte/GetIt/assets/111559776/722f0ac2-4741-40d3-a1bc-3a60c6c592b9)

**Comment by tushitshukla03** [comment]
See routing in nuxt is different. It automatically generate routes based on the provided name in pages section of code. So if you want to look how your page is then after localhost:3000/ type the file name like localhost:3000/yourFilename

**Comment by krushn-a** [comment]
So like if i want to run index.vue so do i have to write localhost:3000/index

**Comment by krushn-a** [comment]
![2023-06-03 (1)](https://github.com/bsoc-bitbyte/GetIt/assets/111559776/518c4ff1-ae27-404c-8442-7eb7eba9e508)

this is the type of folder structure i have

**Comment by krushn-a** [comment]
I tried for localhost:3000 but it still showing this page 
![2023-06-03](https://github.com/bsoc-bitbyte/GetIt/assets/111559776/02bb3f93-2ff3-4703-8e31-b97fb1505361)

**Comment by tushitshukla03** [comment]
First you need to make signup.vue and signin.vue and signup.vue and then you can see it using localhost:3000/signin

**Comment by Priyansh61** [comment]
@krushn-a Are you still facing the issue ? Do you need any help ?

**Comment by krushn-a** [comment]
Thank you for asking, the issue is now solved.

**Comment by Priyansh61** [comment]
@krushn-a Can you give an expected PR date ?

**Comment by krushn-a** [comment]
By 9th my work will be almost completed. So by end of 9th i can send the PR

**Comment by thejaysharma** [comment]
Hey @krushn-a any update ? You have not raised the PR till now.

**Comment by krushn-a** [comment]
Hello @thejaysharma there was some problem with the responsivesness earlier so i couldn't able to push the PR. Here i am attaching the the screen recordings, please let me know if there any more changes required or i should raise the PR.

https://github.com/bsoc-bitbyte/GetIt/assets/111559776/dc401300-095c-4922-b286-52cd62eeedfc


https://github.com/bsoc-bitbyte/GetIt/assets/111559776/d860d906-cdec-4675-ab32-28c1d238acd8
