### ISSUE TITLE
[Feature Request]: Shop page

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#76]
### Is your feature request related to a problem? Please describe.

Make the functional and responsive shop page as given in figma file with tailwind. 
![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/b996946e-fa00-42fe-97d3-138b1eb1ab9a)

### Describe the solution you'd like

Use tailwind and don't change anything in design without discussion.

**Comment by Kushdapush** [comment]
@tushitshukla03 i would like to work on this issue

**Comment by tushitshukla03** [comment]
@Kushdapush sure you can work on this

**Comment by tushitshukla03** [comment]
@Kushdapush updates?

**Comment by Kushdapush** [comment]
Sir i am currently working on the filters functionality, will make a pr as soon as it gets over

**Comment by tushitshukla03** [comment]
@Kushdapush updates?

**Comment by tushitshukla03** [comment]
@Kushdapush
