### ISSUE TITLE
[BUG]: Responsiveness

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#77]
### Describe the bug

Make the cart page mobile friendly.
remove the image(illustration) for mobile view and make  table on the right side go at bottom of cart.

something like this.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/ba71452a-de44-4026-92ba-e163a5ae4bad)

**Comment by abansal15** [comment]
May I work on it I have one issue assigned on bsoc website else you can give this issue to some one else

**Comment by prateekjha1204** [comment]
@tushitshukla03 Sir, i would like to work on this issue, please assign me

**Comment by tushitshukla03** [comment]
@prateekjha1204 You can work on this
