### ISSUE TITLE
[Feature Request]: Product card

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#8]
### Is your feature request related to a problem? Please describe.

Make a product card as per design and make it responsive.

![card](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/f753f5b6-d7e3-471b-aabe-d2ca8c8174e3)

**Figma**: [Link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=76-718&t=N7gzCAsanbXlvwoI-0)

### Describe the solution you'd like

Make the card inside components file.

**Comment by Predcodes69** [comment]
Hello @tushitshukla03,  I am interested in working on this issue, could you please assign this to me?

**Comment by tushitshukla03** [comment]
@Predcodes69 You can work on this.

**Comment by Priyansh61** [comment]
@Predcodes69 Any updates ?

**Comment by Predcodes69** [comment]
@Priyansh61 yes, working on it.

**Comment by Priyansh61** [comment]
@Predcodes69 When will be the PR ready ?

**Comment by Predcodes69** [comment]
@Priyansh61 It will be ready by 10th June.

**Comment by Predcodes69** [comment]
I ran into some problem figuring out tailwind-css into the project application. It is fixed now. I will be ready with the pr soon.
