### ISSUE TITLE
[Feature Request]: Changes in Navbar

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#80]
### Is your feature request related to a problem? Please describe.

The alignment of the navbar should be changed, and the height should be reduced. Please make the required changes as shown in the attached image below.

### Describe the solution you'd like

![Screenshot from 2023-07-14 12-03-23](https://github.com/bsoc-bitbyte/GetIt/assets/104578155/52f63b42-da88-48b1-90f9-97ab4eede1f1)

**Comment by RISHIKESHk07** [comment]
@prernadabi23 I would like contribute to the issue

**Comment by prernadabi23** [comment]
I will assign you once the issue of the navbar routes is completed.
@RISHIKESHk07

**Comment by abansal15** [comment]
@prernadabi23 could you please assign this issue to me ?

**Comment by prernadabi23** [comment]
@RISHIKESHk07 you can start working on it.

**Comment by prernadabi23** [comment]
@RISHIKESHk07 Any updates?

**Comment by RISHIKESHk07** [comment]
@prernadabi23, i am working on it but had a problem with the setup ,resolved as of now.

**Comment by RISHIKESHk07** [comment]
@prernadabi23 in the links there is also a (about us) element , should i remove it?

**Comment by prernadabi23** [comment]
Yes, remove it and use the logo icon instead of the hamburger icon for the navbar menu.

**Comment by RISHIKESHk07** [comment]
@prernadabi23 , i have changed the image but when clicked on it the side bar does not open.
- A video for responsive check, 
  

https://github.com/bsoc-bitbyte/GetIt/assets/117551967/c56754f2-af30-4c61-8d26-b729d27ece7b

**Comment by prernadabi23** [comment]
Just keep the hamburger menu and decrease the height of the navbar, just like in the image; it is too big right now.

**Comment by prernadabi23** [comment]
@RISHIKESHk07 If you are not working, then I will assign someone else.

**Comment by abansal15** [comment]
Please assign it to me I have all my previous issues complete

**Comment by prernadabi23** [comment]
This issue is open if anyone wants to take it.

**Comment by abansal15** [comment]
Please assign me

**Comment by abansal15** [comment]
I have completed all my pre issues

**Comment by prernadabi23** [comment]
@rrtk857 If you want, you can work on #99.

**Comment by prernadabi23** [comment]
Make the navbar close when a user clicks on any nav link.
@abansal15

**Comment by prernadabi23** [comment]
Updates? @abansal15
