### ISSUE TITLE
[BUG]: Changes in the signin and signup pages.

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#81]
### Describe the bug

When viewing the sign-up and sign-in pages, there is a change in the height of the images on both pages, which doesn't look good. There shouldn't be any movement or change in height on either page.

**Comment by Gaur2210** [comment]
Hi @prernadabi23, I am interested in working on this issue, can you please assign it to me?

**Comment by prernadabi23** [comment]
How are you going to proceed? Can you brief me before I assign you?
@Gaur2210

**Comment by Gaur2210** [comment]
I will adjust the dimensions of the images in both the pages, make them similar so as to minimise the visible transition, and adjust the input fields in both according to that.

**Comment by Gaur2210** [comment]
@prernadabi23 
I will adjust the dimensions of the images in both the pages, make them similar so as to minimise the visible transition, and adjust the input fields in both according to that.

**Comment by prernadabi23** [comment]
Okay, then go ahead. Let me know if you have any problems along the way.
@Gaur2210

**Comment by Gaur2210** [comment]
[GetIt.webm](https://github.com/bsoc-bitbyte/GetIt/assets/123197237/8cf24b9b-381c-45ca-bd3e-16f98d4c8903)
@prernadabi23 Could you please review my proposed changes?

**Comment by prernadabi23** [comment]
When can you create a PR?
@Gaur2210
