### ISSUE TITLE
[Feature Request]:  Product page

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#9]
### Is your feature request related to a problem? Please describe.

You need to make the product page design as per figma design.
It is required to use tailwindcss for styling the page.

![Group 107](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/2b0f262f-e918-42f8-b6cf-cc2f7e341f73)

Try to make it responsive.

**Figma** [link](https://www.figma.com/file/w8rDGcgxgDUGzxOzvFX8Eq/Untitled?type=design&node-id=0-1&t=JGyT4UF8QadJWt3u-0)

### Describe the solution you'd like

It will be based on dynamic routing of Nuxt js. 
In the pages directory create a new directory called products and under that create _id.vue which will create a dynamic route of localhost:3000/products/id . Here id is params .
you can also use fakestore api to get fake data so you can design it accordingly. 
fakestoreapi.com/products/id

Example:
![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/296e62a1-3dfe-43ca-82e3-c343b20efc1f)

It's Output:
![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/13decfa6-a9be-4d60-90a3-4b1b40ce90b8)

Now design the page according to figma..

**Comment by rrtk857** [comment]
@tushitshukla03 , I would like to work on this issue. Please assign it to me.

**Comment by tushitshukla03** [comment]
@rrtk857 you can work on this

**Comment by Priyansh61** [comment]
@rrtk857 Can you give an expected date for the PR?

**Comment by rrtk857** [comment]
@Priyansh61 , I will try to do it by Sunday.

**Comment by thejaysharma** [comment]
@rrtk857, Note that you have to use tailwindcss for styling the page.
