### ISSUE TITLE
[Feature Request]: Make add to cart functional

### ISSUE THREAD

**Issue by tushitshukla03** [bsoc-bitbyte/GetIt#90]
### Is your feature request related to a problem? Please describe.

whenever we click add to cart button product with title selected size price and image should get added to cart. 
Also store cart in localStorage so that refreshing does not remove that.
this documentation might help [Link](http://www.voerro.com/en/tutorials/r/simple-persistent-shopping-cart-implementation-with-vuejs-2-and-vuex-in-laravel-5/2)

use the toast to notify anything like please select size or colour
and item has been added to cart like things. use npm package for toast.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/97801384/f916cd6a-f9c7-47a8-aca8-e9b7db8cf956)

### Describe the solution you'd like

use the free api which was used in shop section..

**Comment by abansal15** [comment]
Please assign it to me

**Comment by AkashPaloju** [comment]
i would like to  work on this issue, could u pls assign it to me

**Comment by AkashPaloju** [comment]
i would like to work on this issue, could you please assign it to me

**Comment by tushitshukla03** [comment]
@abansal15 first complete bsoc site isssue

**Comment by abansal15** [comment]
@tushitshukla03 i have send the message that i am not able to fetch the image therefore assign it to somone else

**Comment by abansal15** [comment]
@tushitshukla03  see
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/b1789083-65cd-45df-934a-ce554c58b632)

**Comment by abansal15** [comment]
therefore can you please assign this issue to me?

**Comment by Predcodes69** [comment]
Hello @tushitshukla03 , I am interested in working on this issue, can you please assign it to me?

**Comment by tushitshukla03** [comment]
@AkashPaloju You can work on this

**Comment by AkashPaloju** [comment]
@tushitshukla03 i came to know that my vuex@v4.1.0 is not working well with nuxt@v2.16.3, can i upgrade both vue and nuxt to the latest version in the project

**Comment by tushitshukla03** [comment]
@AkashPaloju update?
