### ISSUE TITLE
[BUG]: Remove the extra space above the sign-in page

### ISSUE THREAD

**Issue by prernadabi23** [bsoc-bitbyte/GetIt#91]
### Describe the bug

![Screenshot from 2023-07-18 22-18-27](https://github.com/bsoc-bitbyte/GetIt/assets/104578155/36c78c29-1019-4bf8-a681-6e24fce0e5b2)

### Expected Behavior

It should be in accordance with the signup page so that there doesn't show any movement

**Comment by shramanpaul** [comment]
I want to work on this issue

**Comment by prernadabi23** [comment]
Sure, it should not take time as it is an easy issue. Let me know if you still encounter any problems.
@shramanpaul
