### ISSUE TITLE
[BUG]: Shop option should not be there on hamburger when we are on shop page on the website

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/GetIt#94]
### Describe the bug

There is option of shop in the hamburger when we are on the shop page itself.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/dc8fe3cc-30cf-47c2-8ece-9b7c1d22aac4)

### Expected Behavior

There should be the option of shop when we are on that page

**Comment by abansal15** [comment]
@prernadabi23 please assign it to me i have all my pre issue complete

**Comment by prernadabi23** [comment]
This is not even the shop page; it's the product page. As you can see, we have already opened an issue on shop page #76 , so you can close this issue.

@abansal15

**Comment by abansal15** [comment]
ok @prernadabi23 i will close this issue but your are saying it is the product page but it opening on clicking shop
