### ISSUE TITLE
[BUG]: Remember me not properly alligned in Galaxy fold phone dimensions

### ISSUE THREAD

**Issue by abansal15** [bsoc-bitbyte/GetIt#95]
### Describe the bug

Remember me is not properly alligned.
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/1ac3f2d3-7a78-4aaa-9172-caa5cb68a3fd)

### Expected Behavior

It should be properly alligned

**Comment by abansal15** [comment]
@prernadabi23 please assign this issue to me

**Comment by prernadabi23** [comment]
Then, also, make the changes in 'Don't have an account?' and 'Sign up for me' on the sign-up page and sign-in page. These should come in one line after another and change only when they don't cover up the entire line.
@abansal15

**Comment by abansal15** [comment]
> Then, also, make the changes in 'Don't have an account?' and 'Sign up for me' on the sign-up page and sign-in page. These should come in one line after another and change only when they don't cover up the entire line. @abansal15

ok

**Comment by abansal15** [comment]
@prernadabi23 done on sign in page
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/f0d604f1-cd27-445c-b22b-7d3893665300)

**Comment by abansal15** [comment]
@prernadabi23 there is no such option of remember me checkbox on dont have an account sign up for free
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/b98219c9-86df-46eb-b6cb-7b62535c7387)

**Comment by prernadabi23** [comment]
For the sign-in page, make "Don't have an account" and "Sign up for me" align on different lines, as you can see in the image; currently, they take up half the space.

For the sign-up page, "Already have an account" and "Sign in" should be aligned on different lines only when they cannot occupy the same line in both cases.

Similarly, for the "Remember me" and "Forgot password" options, they should shift to different lines only when they cannot occupy the same line.

And please refrain from opening issues without consulting any one of the maintainers from now on.

**Comment by abansal15** [comment]
@prernadabi23 done
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/2293aa20-0b1c-4bf9-9db8-573b4dd5f555)
![image](https://github.com/bsoc-bitbyte/GetIt/assets/120590200/23ae233e-71ba-4567-bcbe-78ac33807d00)
